# Generated by Django 5.0.4 on 2024-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=200, verbose_name='Отправитель')),
                ('take', models.CharField(max_length=20, verbose_name='Приниматель')),
                ('msg_txt', models.CharField(max_length=250, verbose_name='Сообщение')),
            ],
        ),
    ]
