# Generated by Django 5.0.4 on 2024-04-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='send',
            field=models.CharField(default='asd', max_length=200, verbose_name='Отправитель'),
        ),
    ]
