# Generated by Django 5.0.4 on 2024-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_alter_msgs_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='take',
            field=models.CharField(default='asd', max_length=20, verbose_name='Приниматель'),
        ),
    ]
