# Generated by Django 5.0.4 on 2024-04-19 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_alter_msgs_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 6, 8, 27, 930221), verbose_name='Дата отправки'),
        ),
    ]
