# Generated by Django 5.0.4 on 2024-04-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_msgs_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='send_date',
            field=models.DateTimeField(default=(2024, 4, 19, 6, 8, 27, 930221), verbose_name='Дата отправки'),
        ),
    ]
